### ISSUE TITLE
 created task list 

### ISSUE THREAD

**Issue by Amarkant20** [Amarkant20/markdown-portfolio#3]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by Amarkant20** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
